version: 2.1

orbs:
  ruby: circleci/ruby@2.0.0
jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.2
    steps:
      - checkout
      - run:
          name: "gem build"
          command: ruby -S gem build *.gemspec 
  test:
    docker:
      - image: cimg/ruby:2.7.2
    steps:
      - checkout
      - run:
          name: "gem test"
          command: |
            ls
            ruby -S sample/samplez.rb 

workflows:
  version: 2.1
  my-workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - test:
          requires:
            - build
